In [1]:
import sys
import pandas as pd
sys.path.insert(0, "/Users/carang/Documents/pycharm document projects/SpotifyProj/docs")
from spotify_loading import load_history, align_end_dates, filter_window

data = "/Users/carang/Documents/pycharm document projects/SpotifyProj/data/"

#fetch the data for both people
cara = load_history(data + "my_spotify_data2 copy.zip", "Cara")
ruby = load_history(data + "ruby_spotify_data copy.zip", "Ruby")

#concatenate both peoples data
both_clean = align_end_dates(pd.concat([cara, ruby], ignore_index=True))

# pick a window
window = input("Select a time frame (all, 30d, 6m, 12m, year): ").strip().lower()

if window == "year":
    year = int(input("Which year? "))
    both_clean = filter_window(both_clean, "year", year)
else:
    both_clean = filter_window(both_clean, window)

print("now in window:" + window)

now in window:all

In [ ]:
#longest song and artist streak
#DONT ADD
from blend_funny_tab import longest_phase

result = longest_phase(both_clean, "Cara", "Ruby")

for person in ["Cara", "Ruby"]:
    art = result[person]["artist"]
    song = result[person]["song"]
    print(f"🔥 {person}'s longest artist phase: {art['name']}, {art['days']} days in a row "
          f"({art['start'].strftime('%b %d, %Y')} – {art['end'].strftime('%b %d, %Y')})")
    print(f"   Longest song streak: {song['name']}, {song['days']} days in a row "
          f"({song['start'].strftime('%b %d, %Y')} – {song['end'].strftime('%b %d, %Y')})\n")

print(f"🏆 Longest phase winner: {result['winner']}")

In [ ]:
from blend_funny_tab import back_to_back_record

result = back_to_back_record(both_clean, "Cara", "Ruby")
#back to back to back plays
#DONT ADD

for person in ["Cara", "Ruby"]:
    r = result[person]
    hours = (r["end"] - r["start"]).total_seconds() / 3600
    print(f"🔂 {person} played {r['track']} by {r['artist']} {r['plays']} times in a row")
    print(f"   {r['start'].strftime('%b %d, %Y %I:%M %p')} → {r['end'].strftime('%I:%M %p')} "
          f"({hours:.1f} hours of just that song)\n")

print(f"🏆 Back-to-back winner: {result['winner']}")

In [ ]:
from blend_funny_tab import forgotten_favorite

result = forgotten_favorite(both_clean, "Cara", "Ruby")
#DONT ADD

for person in ["Cara", "Ruby"]:
    r = result[person]
    if r is None:
        print(f"👻 {person} has never abandoned a favorite. Loyal!\n")
        continue
    print(f"👻 {person}'s forgotten favorite: {r['track']} by {r['artist']}")
    print(f"   It was your #{r['peak_year_rank']} song of {r['peak_year']} ({r['peak_year_plays']} plays)")
    print(f"   You haven't played it since {r['last_played'].strftime('%b %Y')} "
          f"({r['days_since']} days ago)\n")

In [7]:
#Top song in each season! (INDIV) DONT ADD
from blend_funny_tab import top_song_each_season

r = top_song_each_season(both_clean, "Cara", "Ruby")
emojis = {"Spring": "🌸", "Summer": "☀️", "Fall": "🍂", "Winter": "❄️"}

for person in ["Cara", "Ruby"]:
    print(f"{person}:")
    for season, song in r[person].items():
        if song:
            print(f"   {emojis[season]} {season}: {song['track']} by {song['artist']} ({song['plays']} plays)")

Cara:
   🌸 Spring: Magnetic by ILLIT (542 plays)
   ☀️ Summer: WE GO by fromis_9 (151 plays)
   🍂 Fall: Ready to love by SEVENTEEN (344 plays)
   ❄️ Winter: Ditto by NewJeans (315 plays)
Ruby:
   🌸 Spring: One Of Your Girls by Troye Sivan (304 plays)
   ☀️ Summer: WHEN I GO by PRYVT (350 plays)
   🍂 Fall: I Saw Your Face by Malcolm Todd (176 plays)
   ❄️ Winter: GIANTS by True Damage (8 plays)

In [ ]:
#========================================================================================================================================

In [2]:
#most numbner of plays in a day and a week
from blend_funny_tab import loop_record

result = loop_record(both_clean, "Cara", "Ruby")

for person in ["Cara", "Ruby"]:
    r = result[person]
    print(f"🔁 {person} played {r['track']} by {r['artist']} "
          f"{r['plays']} times on {r['date'].strftime('%b %d, %Y')}")

print(f"\n🏆 Loop record winner: {result['winner']}")

from blend_funny_tab import obsession_record

result = obsession_record(both_clean, "Cara", "Ruby")
#most number of plays in a week

for person in ["Cara", "Ruby"]:
    r = result[person]
    print(f"🎧 {person} played {r['track']} by {r['artist']} {r['plays']} times "
          f"from {r['week_start'].strftime('%b %d')} to {r['week_end'].strftime('%b %d, %Y')}")

print(f"\n🏆 Obsession record winner: {result['winner']}")

🔁 Cara played Fame is a Gun by Addison Rae 53 times on Nov 22, 2025
🔁 Ruby played Fuck The Pain Away (Lost Tapes 2022) by Tory Lanez 148 times on Jul 25, 2026

🏆 Loop record winner: Ruby
🎧 Cara played Without Me by Halsey 117 times from Jan 26 to Feb 01, 2026
🎧 Ruby played One Of Your Girls by Troye Sivan 183 times from May 11 to May 17, 2026

🏆 Obsession record winner: Ruby

In [3]:
from blend_funny_tab import ride_or_die

#most consistent song through all the months they have been listening on spotify
#ADD

result = ride_or_die(both_clean, "Cara", "Ruby")

for person in ["Cara", "Ruby"]:
    r = result[person]
    print(f"💍 {person}'s ride-or-die song: {r['track']} by {r['artist']}")
    print(f"   Played in {r['months']} out of {r['active_months']} active months "
          f"({r['first_month']} to {r['last_month']}), {r['plays']} plays total\n")

💍 Cara's ride-or-die song: KAZINO by BIBI
   Played in 41 out of 83 active months (2021-03 to 2026-07), 206 plays total

💍 Ruby's ride-or-die song: I Miss You by MAMAMOO
   Played in 10 out of 13 active months (2020-12 to 2026-09), 46 plays total

In [3]:
#An artist they really like but the other has never touched (SHARED)
from blend_funny_tab import one_person_likes_other_doesnt_touch

r = one_person_likes_other_doesnt_touch(both_clean, "Cara", "Ruby")
for person in ["Cara", "Ruby"]:
    if r[person]:
        print(f"{person}'s #{r[person]['rank']} artist, {r[person]['artist']} "
              f"({r[person]['hours']} hrs), has never been played by the other person.")

Cara's #39 artist, Coldplay (9.8 hrs), has never been played by the other person.
Ruby's #11 artist, Fall Out Boy (20.8 hrs), has never been played by the other person.

In [4]:
#What three song does each person play the most after 12am? (INDIV)
#and the top three shared song after 12am HAHA (SHARED)
from blend_funny_tab import most_plays_after_twelve
from blend_funny_tab import top_shared_after_twelve

indiv = most_plays_after_twelve(both_clean, "Cara", "Ruby")
shared = top_shared_after_twelve(both_clean, "Cara", "Ruby")

for person in ["Cara", "Ruby"]:
    print(f"🌙 {person}'s late night playlist (12am–5am):")
    for i, song in enumerate(indiv[person], start=1):
        print(f"   {i}. {song['track']} by {song['artist']} ({song['plays']} plays)")
    print()

print("🌙 Your shared late night playlist:")
for i, song in enumerate(shared, start=1):
    print(f"   {i}. {song['track']} by {song['artist']} "
          f"(Cara: {song['Cara']} · Ruby: {song['Ruby']})")

🌙 Cara's late night playlist (12am–5am):
   1. Bags by Clairo (80 plays)
   2. Fame is a Gun by Addison Rae (74 plays)
   3. Let Me Love You by DJ Snake (63 plays)

🌙 Ruby's late night playlist (12am–5am):
   1. Selfless by The Strokes (183 plays)
   2. I Saw Your Face by Malcolm Todd (161 plays)
   3. Sweet Boy by Malcolm Todd (144 plays)

🌙 Your shared late night playlist:
   1. Bleed (feat. Omar Apollo) by Malcolm Todd (Cara: 20 · Ruby: 43)
   2. SLOW DANCING IN THE DARK by Joji (Cara: 18 · Ruby: 67)
   3. Roommates by Malcolm Todd (Cara: 16 · Ruby: 144)

In [5]:
#Which artist took over a users life in one month(biggest percentage of listening was one artist) (INDIV)
#only count months with over 10 hours of listening
from blend_funny_tab import biggest_percent_of_month_artist

r = biggest_percent_of_month_artist(both_clean, "Cara", "Ruby")
for person in ["Cara", "Ruby"]:
    if r[person]:
        x = r[person]
        print(f"👑 {person}: in {x['month']}, {x['artist']} was {x['share']:.0%} of everything "
              f"({x['artist_hours']} of {x['month_hours']} hours)")

👑 Cara: in 2026-01, BTS was 17% of everything (19.6 of 115.2 hours)
👑 Ruby: in 2026-09, Malcolm Todd was 36% of everything (108.3 of 299.9 hours)

In [6]:
#Shared obsession song (song that both people have played the most in one day) (SHARED)
from blend_funny_tab import top_shared_song_one_day

r = top_shared_song_one_day(both_clean, "Cara", "Ruby")
if r:
    print(f"🔂 Your shared obsession song: {r['track']} by {r['artist']}")
    for person in ["Cara", "Ruby"]:
        print(f"   {person}'s record: {r[person]['plays']} plays on {r[person]['date']}")

🔂 Your shared obsession song: Sweet Boy by Malcolm Todd
   Cara's record: 14 plays on 2025-10-13
   Ruby's record: 32 plays on 2026-05-26

In [7]:
#What hour you guys are most likely to be listening at the same time,
#and what is each persons top song (SHARED)
from blend_funny_tab import top_shared_hour_top_song

r = top_shared_hour_top_song(both_clean, "Cara", "Ruby")
start = r["hour"]
end = (r["hour"] + 1) % 24
time_range = f"{start:02d}:00–{end:02d}:00"

print(f"🪞 You two are most likely to be listening at the same time between {time_range}.")
print(f"   That's when {r['Cara']['share']:.0%} of Cara's and {r['Ruby']['share']:.0%} of Ruby's listening happens.\n")

for person in ["Cara", "Ruby"]:
    x = r[person]
    print(f"   {person}'s most-played song at {r['hour']}:00, across all of their Spotify history:")
    print(f"   {x['track']} by {x['artist']} ({x['plays']} plays)\n")

🪞 You two are most likely to be listening at the same time between 00:00–01:00.
   That's when 8% of Cara's and 8% of Ruby's listening happens.

   Cara's most-played song at 0:00, across all of their Spotify history:
   Bags by Clairo (23 plays)

   Ruby's most-played song at 0:00, across all of their Spotify history:
   One Of Your Girls by Troye Sivan (41 plays)

In [8]:
#The song each person goes out of their way to click on the most (INDIV)
from blend_funny_tab import top_clicked_song

r = top_clicked_song(both_clean, "Cara", "Ruby")
for person in ["Cara", "Ruby"]:
    if r[person]:
        x = r[person]
        print(f"👆 The song {person} goes out of their way to play the most: "
              f"{x['track']} by {x['artist']} (tapped {x['clicks']} times)")

👆 The song Cara goes out of their way to play the most: Bags by Clairo (tapped 328 times)
👆 The song Ruby goes out of their way to play the most: One Of Your Girls by Troye Sivan (tapped 28 times)

In [9]:
#Which season shares the most listening, and top 5 indiv and shared songs in the season (SHARED & INDIV)
from blend_funny_tab import top_shared_season_songs

r = top_shared_season_songs(both_clean, "Cara", "Ruby")
emojis = {"Spring": "🌸", "Summer": "☀️", "Fall": "🍂", "Winter": "❄️"}

print(f"{emojis[r['season']]} You two listen the most in {r['season']}!")
print(f"   {r['shares']['Cara']:.0%} of Cara's and {r['shares']['Ruby']:.0%} of Ruby's listening happens then.\n")

for person in ["Cara", "Ruby"]:
    print(f"   {person}'s {r['season']} playlist:")
    for i, s in enumerate(r[person], start=1):
        print(f"      {i}. {s['track']} by {s['artist']} ({s['plays']} plays)")
    print()

print(f"   Your shared {r['season']} playlist:")
for i, s in enumerate(r["shared"], start=1):
    print(f"      {i}. {s['track']} by {s['artist']} (Cara: {s['Cara']} · Ruby: {s['Ruby']})")

☀️ You two listen the most in Summer!
   28% of Cara's and 58% of Ruby's listening happens then.

   Cara's Summer playlist:
      1. FUCK THE SPEAKERZ UP by ISOxo (110 plays)
      2. SIGNAL by ISOKNOCK (97 plays)
      3. dashstar* - VIP by Knock2 (88 plays)
      4. Fever by Buckshot (83 plays)
      5. I Wish you Roses by Kali Uchis (74 plays)

   Ruby's Summer playlist:
      1. WHEN I GO by PRYVT (350 plays)
      2. I Saw Your Face by Malcolm Todd (282 plays)
      3. Roommates by Malcolm Todd (270 plays)
      4. You Owe Me by Malcolm Todd (268 plays)
      5. Selfless by The Strokes (266 plays)

   Your shared Summer playlist:
      1. SLOW DANCING IN THE DARK by Joji (Cara: 35 · Ruby: 174)
      2. hate that i made you love me by Ariana Grande (Cara: 32 · Ruby: 25)
      3. Roommates by Malcolm Todd (Cara: 25 · Ruby: 270)
      4. Bleed (feat. Omar Apollo) by Malcolm Todd (Cara: 20 · Ruby: 34)
      5. X's & O's by Malcolm Todd (Cara: 18 · Ruby: 65)

In [10]:
#What month of the year do you both listen to the most, and your top songs in it (SHARED)
from blend_funny_tab import top_shared_month_songs

r = top_shared_month_songs(both_clean, "Cara", "Ruby")

print(f"📅 You two go hardest in {r['month']}!")
print(f"   {r['shares']['Cara']:.0%} of Cara's and {r['shares']['Ruby']:.0%} of Ruby's listening happens in {r['month']}.\n")

for person in ["Cara", "Ruby"]:
    print(f"   {person}'s {r['month']} playlist:")
    for i, s in enumerate(r[person], start=1):
        print(f"      {i}. {s['track']} by {s['artist']} ({s['plays']} plays)")
    print()

print(f"   Your shared {r['month']} playlist:")
for i, s in enumerate(r["shared"], start=1):
    print(f"      {i}. {s['track']} by {s['artist']} (Cara: {s['Cara']} · Ruby: {s['Ruby']})")

📅 You two go hardest in June!
   12% of Cara's and 22% of Ruby's listening happens in June.

   Cara's June playlist:
      1. 풀어 by DEAN (56 plays)
      2. ON THE TABLE (feat. Sik-K) by DIMO REX (53 plays)
      3. WDA (Whole Different Animal) (feat. G-DRAGON) by aespa (49 plays)
      4. E85 by Don Toliver (49 plays)
      5. Fever by Buckshot (43 plays)

   Ruby's June playlist:
      1. WHEN I GO by PRYVT (199 plays)
      2. Hotel Room by Ax and the Hatchetmen (128 plays)
      3. Sweet Boy by Malcolm Todd (125 plays)
      4. You Owe Me by Malcolm Todd (122 plays)
      5. Roommates by Malcolm Todd (119 plays)

   Your shared June playlist:
      1. Roommates by Malcolm Todd (Cara: 21 · Ruby: 119)
      2. Obsessica by Malcolm Todd (Cara: 17 · Ruby: 51)
      3. Ain't That The Truth by Malcolm Todd (Cara: 14 · Ruby: 26)
      4. Malcolm In The Middle by Malcolm Todd (Cara: 12 · Ruby: 14)
      5. Earrings by Malcolm Todd (Cara: 12 · Ruby: 107)

In [11]:
#songs that one person hella loves but the other has never listened to
from blend_funny_tab import steal_list

cara_needs = steal_list(both_clean, giver="Ruby", receiver="Cara")
ruby_needs = steal_list(both_clean, giver="Cara", receiver="Ruby")

display(cara_needs)
display(ruby_needs)

person                                                            Ruby  Cara
track                                      artist
WHEN I GO                                  PRYVT                   418     0
Make Me a Better Man                       Malcolm Todd            315     1
Selfless                                   The Strokes             298     1
Rodrick Rules                              Malcolm Todd            239     0
エロティック                                     Lily Chou-Chou          231     0
Who's the Fool                             Malcolm Todd            231     0
Rockstar Boyfriend                         Malcolm Todd            229     0
Hotel Room                                 Ax and the Hatchetmen   200     1
Cheer Me On                                Malcolm Todd            198     1
Thailand                                   Malcolm Todd            187     1
Lovebird                                   Malcolm Todd            183     0
Ladygirl                                   Malcolm Todd            179     0
Cute Shirt (Interlude)                     Malcolm Todd            168     0
I'll Never Love Again                      WOODZ                   161     1
Art House                                  Malcolm Todd            159     0
Nowhere You Are                            SUNGJIN                 155     0
Concrete                                   Malcolm Todd            151     0
飛べない翼                                      Lily Chou-Chou          150     0
I don’t wanna lose                         SUNGJIN                 149     0
Evangeline                                 Stephen Sanchez         149     0
The Subway                                 Chappell Roan           142     1
"L"                                        The Volunteers          139     0
Luv me                                     AOA                     136     1
Today is a diamond - Full Spec Edition     桐生一馬(黒田崇矢)              135     0
CINEMA                                     WOODZ                   132     0
Missing You (Feat. Kim Yuna)               G-DRAGON                131     1
Edifice                                    JILUKA                  127     0
die                                        BUCK-TICK               127     0
Secret Tape                                SUNMI                   124     0
Past Won't Leave My Bed                    Joji                    124     0
Holy Grail                                 JAŸ-Z                   124     0
When I Was Your Man                        Bruno Mars              120     0
Party 4 Martians                           Tory Lanez              118     0
How Can I Go On - New Orchestrated Version Freddie Mercury         109     0
She's in someone's locket                  The Volunteers          106     0
ABYSS                                      WOODZ                   105     0
No Tears On The Dancefloor                 LEE CHAEYEON            100     1
向日葵 (Imprinted)                            &TEAM                    99     0
AMERICAN DREAMS                            Tiger La Flor            96     0
TOXIC                                      MEOVV                    94     0
絵本                                         Sān-Z                    94     0
You know that                              AOA                      93     0
POP DAT THANG                              DaBaby                   88     1
金木犀の夜                                      Kinokoteikoku            80     0
高嶺の花子さん                                    back number              78     0
FORGETTING YOUR KISS                       Stephen Sanchez          76     1
The Symphony of Fxxkboys                   Whee In                  75     0
Mr. Loverman                               Ricky Montgomery         72     0
the feeling                                Steve Lacy               63     2
Why Can't You Love Me?                     WENDY                    61     0

person                                                          Cara  Ruby
track                                         artist
dimple                                        BTS                262     0
It's ok I'm ok                                Tate McRae         250     0
Let Me Love You                               DJ Snake           230     0
Without Me                                    Halsey             221     0
Side To Side                                  Ariana Grande      195     2
I Wish you Roses                              Kali Uchis         165     0
COMË N GO                                     Yeat               155     2
Fever                                         Buckshot           145     0
Sports car                                    Tate McRae         135     0
Heavy                                         The Marías         130     1
Pinball                                       RESCENE            129     1
Autumn Leaves                                 BTS                123     0
theclubrock                                   Benny Bellson      116     0
Stateside + Zara Larsson                      PinkPantheress     111     2
Pied Piper                                    BTS                111     0
Buzzcut Season                                Lorde              110     0
You Know You Like It                          DJ Snake           108     0
DON'T WANNA MISS THIS                         Restricted         104     0
Night , Blooming Jasmine .                    fakemink           103     1
Girl, so confusing featuring lorde            Charli xcx         103     0
MONTAGEM HIKARI                               BellyJay           100     0
jeans                                         2hollis             96     1
Bass Cannon (Flux's Version) - Crankdat Remix Flux Pavilion       95     0
Just Keep Watching (From F1® The Movie)       Tate McRae          94     1
Zoo - From "Zootopia 2"                       Disney              93     0
Von dutch                                     Charli xcx          90     0
Lean On                                       Major Lazer         90     0
Slow Dance                                    Clairo              88     1
Raindance (feat. Tems)                        Dave                84     0
4EVER                                         Clairo              83     0
That’s So True                                Gracie Abrams       82     0
STFU                                          Crankdat            82     1
Bags - Recorded At Electric Lady Studios      Clairo              81     1
Like a taxi (Oh well)                         Cece Natalie        79     0
Around Me                                     sincerely Lue.      75     0
Roses                                         The Chainsmokers    72     1
Folded                                        Kehlani             71     0
I Want You To Know                            Zedd                71     2
Exitin                                        Cece Natalie        69     0
Sorry                                         Justin Bieber       69     1
Deja Vu                                       RESCENE             69     0
E85                                           Don Toliver         68     2
In the Name of Love                           Martin Garrix       68     0
Company                                       Justin Bieber       68     0
SMACK TALK                                    ISOxo               68     1
STARsound (pt2)                               ISOxo               68     2
Only in My Dreams                             The Marías          67     0
Secondhand (feat. Rema)                       Don Toliver         66     0
B2b                                           Charli xcx          65     0
Propaganda                                    DJ Snake            64     1

In [2]:
import main
main.both_clean = both_clean

In [3]:
import json

print(json.dumps(json.loads(main.get_game("Cara", "Ruby")), indent=2))

[
  {
    "title": "Top played song in a day",
    "cards": [
      {
        "prompt": "The song Cara listened to the most in one day:",
        "answer": "Magnetic by ILLIT",
        "detail": "149 plays on 2024-03-26"
      },
      {
        "prompt": "The song Ruby listened to the most in one day:",
        "answer": "Fuck The Pain Away (Lost Tapes 2022) by Tory Lanez",
        "detail": "148 plays on 2026-07-25"
      }
    ]
  },
  {
    "title": "Artists unique to each other",
    "cards": [
      {
        "prompt": "The artist Cara loves but Ruby has never listened to:",
        "answer": "Kato",
        "detail": "Cara's #49 artist \u00b7 23.1 hours"
      },
      {
        "prompt": "The artist Ruby loves but Cara has never listened to:",
        "answer": "Fall Out Boy",
        "detail": "Ruby's #12 artist \u00b7 20.9 hours"
      }
    ]
  }
]